[platformio]
default_envs = esp32dev
data_dir = data

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  mobizt/ReadyMail@^0.4.2
  mobizt/ESP_SSLClient@^2.1.0
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -D CORE_DEBUG_LEVEL=1
